apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-pihole
  namespace: argocd
spec:
  project: default
  source:
    path: charts/pihole
    repoURL: https://github.com/MoJo2600/pihole-kubernetes
    targetRevision: bfc0351af6501b19f84a5f08514bdc0b887f3703 #using version number 2.11.0 kept returning errors but I was able to use git commit hash instead
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
